builds:
  - binary: check-sakura-object-storage-usage
    goos:
      - linux
    goarch:
      - amd64
      - arm64
archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
release:
  github:
    owner: u5surf
    name: check-sakura-object-storage-usage
